### ISSUE TITLE
Add Java 8 to travis config

### ISSUE THREAD

**Issue by berezovskyi** [ldp4j/eswc2015-tutorial#8]
Use Java 8 alongside Java 7. Travis supports Java 8 [since 2013](https://blog.travis-ci.com/2013-11-26-test-your-java-libraries-on-java-8/).

I will submit a PR for this.

**Comment by mestebangutierrez** [comment]
It is not as straightforward as it seems. If you have a look at the Travis CI configuration file, we leverage Travis for delivering the artifacts build. If we execute the process for Java 7 and Java 8 only the latest artifacts will be available after the build. In this case, only the Java 8 version of the binaries. As you may know Java 8 class file format is not backwards compatible with that of Java 7, therefore Java 8 binaries cannot be executed in Java 6/7 VMs.

We have to think about this because this change would impact our day-to-day work, as Java 7 is still the version used in production.

**Comment by berezovskyi** [comment]
I see, I didn't know about the issue with latest artifacts.
